apiVersion: v1
kind: Service
metadata:
  labels:
    app: planning-poker
  name: planning-poker-service
  namespace: planning-poker
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 3000
  selector:
    app: planning-poker
  sessionAffinity: None
  type: LoadBalancer
  loadBalancerIP: 34.73.100.103
